### ISSUE TITLE
DID：Motif的显示不正确

### ISSUE THREAD

**Issue by mave99a** [blocklet/auth-demo#17]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/41923/160805196-603b065e-ff0a-44d0-95c1-64cad5f08439.png">

**Comment by linchen1987** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/11010275/160981554-16cabe8c-3d5a-4e25-8926-e857e84c1027.png">

@mave99a 错误指的是这两个 头像预期是一样，实际不一样？是否换了账号？

**Comment by mave99a** [comment]
不只是这两个。 你可以自己测试下。 

上面的robert都是我，会每次变。

**Comment by linchen1987** [comment]
请提供一下
- blocklet server 版本
- auth demo 版本
- 浏览器

我本地测试正常
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/11010275/160984236-fe5d9bb4-ad78-43ba-9a81-7ccfeb078b85.png">

**Comment by linchen1987** [comment]
我用 safari 和 edge 测试正常 https://auth-demo-tat-18-180-145-193.ip.abtnet.io/?locale=en 

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/11010275/160984486-d86b4964-a0bf-4f39-86f9-50aa1bcacb06.png">

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/11010275/160984637-32f1fd94-b35b-41aa-ba4c-e5db4ba83e14.png">

**Comment by mave99a** [comment]
奇怪，现在的确正确了。 但你看到我最上面那个截屏的did motif 和现在这个里的历史消息，有很大区别。 

不知道在什么情况下会出现这种问题。

**Comment by mave99a** [comment]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/41923/160993259-37f58858-2bf4-4538-accd-49a520d22da5.png">

多用几次，repro了， 你看下这一条 和你上一屏的区别。 应该是和update了屏幕内容相关

**Comment by linchen1987** [comment]
我这里在评论后不刷新页面时，新增评论的头像时错的，刷新页面后正常。

和你的现象不太一样

<img width="802" alt="image" src="https://user-images.githubusercontent.com/11010275/161166751-1c1daa58-4608-48ac-93a1-38a432495a39.png">

**Comment by mave99a** [comment]
两种错误都出现过。 总之有问题

**Comment by mave99a** [comment]
感觉就是下面的did motif 没刷新，还是老的。 只要页面refresh 就正确了。

**Comment by mave99a** [comment]
看下这个是不是相关的：
- https://github.com/ArcBlock/blocklet-server/issues/4417 

如果是的话这个PR 可能fix了：
https://github.com/ArcBlock/ux/pull/549#pullrequestreview-934605445

**Comment by donotlb** [comment]
> 看下这个是不是相关的：
> 
> * [icon 不一致 ArcBlock/blocklet-server#4417](https://github.com/ArcBlock/blocklet-server/issues/4417)
> 
> 如果是的话这个PR 可能fix了： [ArcBlock/ux#549 (review)](https://github.com/ArcBlock/ux/pull/549#pullrequestreview-934605445)

应该同样的原因，我稍后验证一下

**Comment by donotlb** [comment]
开发环境升级最新 did connect 依赖后表现正常, 暂未发版, 先 close 了
