### ISSUE TITLE
blocklet dev

### ISSUE THREAD

**Issue by wuwei111467** [blocklet/auth-demo#3]
![image](https://user-images.githubusercontent.com/13595350/110267022-f3df1600-7ff9-11eb-87b7-189cdcbf59ec.png)

**Comment by linchen1987** [comment]
abtnode 的版本是？ 执行 `abtnode -V` 查看 abtnode 版本

**Comment by linchen1987** [comment]
可以尝试升级 abtnode 到最新版（1.2.3），在项目根目录下删除 `.abtnode` 目录，然后重新执行 `abtnode init -f --mode debug` `abtnode start` `blocklet dev`

**Comment by wuwei111467** [comment]
更新到1.2.13版本 启动还是报同样的问题

**Comment by linchen1987** [comment]
问题是因为本地创建的 abtnode 没有配置 nginx。将 abtnode 升至最新版。新版本的 abtnode 在创建时会强制配置 nginx
